### PR TITLE
Add .gitignore, makedoc.g; remove generated files from repo; tweak testall.g

### PR DESCRIPTION
**Pull request by fingolfin**
These are purely technical changes, which help making release of this package using https://github.com/gap-system/ReleaseTools

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
Standard things, look good to me. @Stefan-Kohl ?

**Comment by Stefan-Kohl** [comment]
@alex-konovalov Probably yes. -- Though lacking write access to this repository, I cannot merge.

**Comment by olexandr-konovalov** [comment]
@Stefan-Kohl just to check, do you know how to "Rebase and merge" instead of creating a merge commit? See https://github.com/blog/2243-rebase-and-merge-pull-requests

**Comment by fingolfin** [comment]
@Stefan-Kohl you have write access now to both repositories, sorry about forgetting to set that up!

I have a few more tweaks coming up, though, so you might want to wait with merging this (and actually, I would suggest to not use the "Merge pull request" button, but rather switch to "Rebase and merge", as described in the link @alex-konovalov posted above)

**Comment by Stefan-Kohl** [comment]
@fingolfin Thank you! -- Though while all this so far looks harmless, one key point: when making changes to the code, always make sure that RCWA still works afterwards. -- RCWA strongly relies on how exactly residue class unions behave, so nontrivial changes in ResClasses will normally require changes in RCWA as well.

**Comment by fingolfin** [comment]
@Stefan-Kohl absolutely! Note that this PR should not touch the actually functionality of resclasses or rcwa in any way, it is purely "janitorial". I did not touch any files in `lib`. So I hope it'll be fine.

What you say suggests to me that perhaps the travis setup for this package (which I just added to this PR) should perhaps be augmented to also run the test of the (latest) rcwa package, to catch regressions immediately (assuming the tests reveal them). Doing that is beyond what I have time to work on, but we could write an issue to remember this, and add it at a later date.

**Comment by Stefan-Kohl** [comment]
@fingolfin Yes, scheduling automated tests of RCWA after changes in ResClasses would certainly be a good idea. -- When I made changes to ResClasses, so far I always ran RCWA's tests afterwards manually. For extended testing before a release or so, there is the possibility to run the manual examples via RCWATestExamples().

**Comment by fingolfin** [comment]
This is now ready for "rebase & merge".

**Pull request merged**
