### PR TITLE
Restrict filters for two \- methods

### PR DESCRIPTION
**Pull request by fingolfin**
The new filters match the info string of the methods.

Resolves point 6 of https://github.com/gap-system/gap/issues/2164

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
@Stefan-Kohl merging this without reviewing was a but rushed through. One should be able to see that tests failed with two diffs:
```
########> Diff in /home/travis/build/gap-packages/resclasses/gaproot/pkg/rescl\
asses/tst/resclass.tst:372
# Input is:
45-Integers;
# Expected output:
Integers
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `-' on 2 arguments
########
########> Diff in /home/travis/build/gap-packages/resclasses/gaproot/pkg/rescl\
asses/tst/resclass.tst:376
# Input is:
1-Z_pi([2,3]);
# Expected output:
Z_( 2, 3 )
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `-' on 2 arguments
########
```
To compare, a fresh (~16 hours ago) test of the clone of this repository in the master branch of GAP passed without diffs.

I also don't know how RCWA responds on these changes - perhaps a proper review should also include testing RCWA with these changes too.

**Comment by Stefan-Kohl** [comment]
@alex-konovalov I assumed that @fingolfin has tested this before committing (usual test: ResClasses' tests plus RCWA's tests plus manual examples of both packages).

**Comment by olexandr-konovalov** [comment]
That's fine, we should be able to fix that. 

Also, in case of any doubts, it would be totally acceptable to ask @fingolfin how did he test it. Then, even if he tested, that was on _his_ environment, where it may interact with other changes, locally installed package etc., so it may work for him, but fail in Travis tests - and since the PR displays "The Travis CI build failed" then whatever we may assume about the testing is already questionable, since  we want PR tests to pass on Travis, with exceptions only when justified.

Also, if it would be me testing, then I'd only run the default tests (those which `TestPackage` calls) as I do not now how to invoke other tests. Are manual example tests not a part of the default test?

Finally, with Travis running tests automatically, what we usually do nowadays is to push changes to a branch and submit a PR, since then it will be tested, and you can edit the PR and massage the code and tests until satisfactory level. So next time please don't assume that anything is working :)

Anyhow, how to fix that? Are those failing examples essential for the package functionality?

**Comment by Stefan-Kohl** [comment]
@alex-konovalov: Well, how to fix that? -- Unless you are happy to take a closer look at this, the way to go is just to revert the change, I think. If there are particular problems with this approach which need fixing, changes may be possible -- though depending on what it is, it may need some thought. -- If you would like to achieve that expressions like Integers-1 or 1+Integers or [1,0]+Integers^2 don't evaluate to what they evaluate to now, this will require you to look into how to adapt the code. Likely not impossible, but I'd expect things to get uglier and you'd probably need workarounds for a number of such cases in different places. 

As to the examples test -- this is run by ResClassesTestExamples(); and is not part of the default test suite. The same holds for RCWA / RCWATestExamples(); . But in general the default tests should catch most problems.

**Comment by olexandr-konovalov** [comment]
I am not interested in having `Integers-1` or `1+Integers` or `[1,0]+Integers^2`, but my question is: if we will withdraw this ability, are there any other parts of package functionality that will suffer?

**Comment by Stefan-Kohl** [comment]
@alex-konovalov I think my last comment has already answered your question. -- What is still unclear to you?

**Comment by olexandr-konovalov** [comment]
@Stefan-Kohl what else became broken? Is there are only two test examples, can we just remove them? It will still work for objects `IsResidueClassUnion`, what I believe is the primary goal of this package.

**Comment by Stefan-Kohl** [comment]
@alex-konovalov No, the test examples cannot just be removed. They are there on purpose. As I said, if you are willing to spend time to take a closer look and implement suitable workarounds, you may be able to make the two methods superfluous (but you'd need to check). The underlying concept is that the residue class 0 (modulo 1) is represented by the corresponding ring object. If you want to get rid of the methods, you either need to change this (ugly and a lot of work) or implement some workarounds. In any case you would need to consider both packages (RCWA and ResClasses).

**Comment by fingolfin** [comment]
Hi, I wasn't aware of the discussion here, and only noticed it by chance now. I did not really test the changes thoroughly -- these days, I often rely on Travis to run tests for me. I would have addressed the failing tests here of course, but as this was merged, I never even saw them, and the PR vanished from my list of "in progress" PRs.

Anyway, I'll take a look at the regression now, and either submit a fix, or a PR reverting it.

**Pull request merged**
